# Generated by Django 6.0.5 on 2026-06-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('muestra', '0003_initial'),
        ('paciente', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametro',
            options={'ordering': ['orden', 'nombre_parametro'], 'verbose_name': 'Parámetro', 'verbose_name_plural': 'Parámetros'},
        ),
        migrations.AddField(
            model_name='parametro',
            name='grupo',
            field=models.CharField(blank=True, help_text="Sección visual, ej: 'Eritrograma', 'Leucograma %', 'Leucograma absoluto'", max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='opciones',
            field=models.JSONField(blank=True, help_text="Para tipo SELECT: ['-','+','++']", null=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parametro',
            name='tipo_dato',
            field=models.CharField(choices=[('NUM', 'Numérico'), ('TXT', 'Texto libre'), ('SEL', 'Selección')], default='NUM', max_length=3),
        ),
        migrations.AddField(
            model_name='valorreferencia',
            name='sexo',
            field=models.CharField(choices=[('A', 'Ambos'), ('M', 'Macho'), ('H', 'Hembra')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='valorreferencia',
            name='texto_referencia',
            field=models.CharField(blank=True, help_text="Para parámetros no numéricos, ej '-a +'", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinario_solicitante', models.CharField(blank=True, max_length=120)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PROC', 'En proceso'), ('VALD', 'Validado'), ('ENTR', 'Entregado'), ('ANUL', 'Anulado')], default='PEND', max_length=4)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado_por', models.CharField(blank=True, max_length=120)),
                ('validado_por', models.CharField(blank=True, max_length=120)),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('alteraciones', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('pronostico', models.CharField(blank=True, max_length=120)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_examen', to='catalogo.examen')),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_examen', to='muestra.muestra')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='catalogo.ordentrabajo')),
            ],
            options={
                'unique_together': {('orden', 'examen')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('valor_texto', models.CharField(blank=True, max_length=150)),
                ('interpretacion', models.CharField(blank=True, max_length=10)),
                ('orden_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='catalogo.ordenexamen')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='catalogo.parametro')),
            ],
            options={
                'unique_together': {('orden_examen', 'parametro')},
            },
        ),
    ]
