# Generated by Django 6.0.5 on 2026-05-25 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_examen', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='catalogo.catalogoexamen')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
                'ordering': ['nombre_examen'],
            },
        ),
    ]
