# Generated by Django 6.0.5 on 2026-06-27 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_parametro_options_parametro_grupo_and_more'),
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='requiere_muestra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='tipo_muestra_sugerida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='resultados/'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='detalle_solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_examen', to='recepcion.detallesolicitud'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='recepcion.solicitudexamen'),
        ),
    ]
