# Generated by Django 6.0.5 on 2026-05-25 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parametro', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='catalogo.examen')),
            ],
            options={
                'verbose_name': 'Parámetro',
                'verbose_name_plural': 'Parámetros',
                'ordering': ['nombre_parametro'],
            },
        ),
        migrations.CreateModel(
            name='ValorReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('especie', models.CharField(blank=True, max_length=50, null=True)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_referencia', to='catalogo.parametro')),
            ],
            options={
                'verbose_name': 'Valor de Referencia',
                'verbose_name_plural': 'Valores de Referencia',
                'ordering': ['parametro'],
            },
        ),
    ]
