# Generated by Django 6.0.5 on 2026-06-29 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_examen_requiere_muestra_examen_tipo_muestra_sugerida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('validado', 'Validado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='veterinario_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_responsable', to=settings.AUTH_USER_MODEL),
        ),
    ]
