# Generated by Django 6.0.5 on 2026-06-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ci',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
