# Generated by Django 6.0.5 on 2026-07-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si es True, el usuario debe cambiar su contraseña temporal antes de continuar.'),
        ),
    ]
