# Generated by Django 6.0.5 on 2026-07-02 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to='usuarios.permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuario',
                'unique_together': {('usuario', 'permiso')},
            },
        ),
    ]
