# Generated by Django 6.0.5 on 2026-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('clinica_procedencia', models.CharField(blank=True, max_length=200, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Médico Veterinario',
                'verbose_name_plural': 'Médicos Veterinarios',
            },
        ),
    ]
