# Generated by Django 6.0.5 on 2026-06-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoveterinario',
            name='ci',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
