# Generated by Django 6.0.5 on 2026-06-22 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_medicoveterinario_ci'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicoveterinario',
            options={'verbose_name': 'Médico Veterinario', 'verbose_name_plural': 'Médicos Veterinarios'},
        ),
        migrations.RenameField(
            model_name='medicoveterinario',
            old_name='direccion',
            new_name='clinica_procedencia',
        ),
        migrations.RemoveField(
            model_name='medicoveterinario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='medicoveterinario',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='medicoveterinario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='medicoveterinario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='medicoveterinario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='medicoveterinario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico_perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
