# Generated by Django 6.0.5 on 2026-06-23 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
        ('propietario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentepaciente',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antecedentes_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='propietario.propietario'),
        ),
        migrations.AddField(
            model_name='antecedentepaciente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='raza',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razas', to='paciente.especie'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='raza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='paciente.raza'),
        ),
        migrations.AlterUniqueTogether(
            name='raza',
            unique_together={('nombre', 'especie')},
        ),
    ]
