# Generated by Django 6.0.5 on 2026-05-25 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_historialclinico_raza'),
        ('propietario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sexo', models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra'), ('desconocido', 'Desconocido')], max_length=20, null=True)),
                ('tamanio', models.CharField(blank=True, choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('historial_clinico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='paciente.historialclinico')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='propietario.propietario')),
                ('raza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='paciente.raza')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nombre'],
            },
        ),
    ]
