# Generated by Django 6.0.5 on 2026-05-25 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_paciente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='historial_clinico',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AntecedentePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('enfermedad_cronica', 'Enfermedad crónica'), ('cirugia', 'Cirugía previa'), ('alergia', 'Alergia'), ('vacuna', 'Vacuna'), ('medicamento', 'Medicamento habitual'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='paciente.paciente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antecedentes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Antecedente del Paciente',
                'verbose_name_plural': 'Antecedentes del Paciente',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
