# Generated by Django 6.0.5 on 2026-05-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_remove_historialclinico_usuario_and_more'),
        ('recepcion', '0003_remove_solicitudexamen_historial_clinico_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialClinico',
        ),
    ]
