# Generated by Django 6.0.5 on 2026-06-22 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='propietario',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
