# Generated by Django 6.0.5 on 2026-05-25 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_remove_historialclinico_usuario_and_more'),
        ('recepcion', '0002_solicitudexamen_detallesolicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudexamen',
            name='historial_clinico',
        ),
        migrations.AddField(
            model_name='solicitudexamen',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='paciente.paciente'),
        ),
    ]
