# Generated by Django 6.0.5 on 2026-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incidencia de Muestra',
                'verbose_name_plural': 'Incidencias de Muestras',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_muestra', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_proceso', 'En proceso'), ('procesada', 'Procesada'), ('descartada', 'Descartada')], default='recibida', max_length=50)),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('validado', 'Validado')], default='pendiente', max_length=20)),
                ('valores_obtenidos', models.JSONField(blank=True, help_text="Valores del examen en formato JSON. Ej: {'glucosa': '95 mg/dL'}", null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='PDF del resultado generado', null=True, upload_to='resultados/')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
