# Generated by Django 6.0.5 on 2026-06-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incidencia de Muestra',
                'verbose_name_plural': 'Incidencias de Muestras',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_muestra', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_proceso', 'En proceso'), ('procesada', 'Procesada'), ('descartada', 'Descartada')], default='recibida', max_length=50)),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['codigo'],
            },
        ),
    ]
