# Generated by Django 6.0.5 on 2026-05-25 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muestra', '0001_initial'),
        ('recepcion', '0002_solicitudexamen_detallesolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras', to='recepcion.solicitudexamen'),
        ),
        migrations.AddField(
            model_name='incidenciamuestra',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='muestra.muestra'),
        ),
    ]
