# Generated by Django 6.0.5 on 2026-06-22 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0002_initial'),
        ('recepcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('validado', 'Validado')], default='pendiente', max_length=20)),
                ('valores_obtenidos', models.JSONField(blank=True, help_text="Valores del examen en formato JSON. Ej: {'glucosa': '95 mg/dL'}", null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='PDF del resultado generado', null=True, upload_to='resultados/')),
                ('detalle_solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='recepcion.detallesolicitud')),
                ('muestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='muestra.muestra')),
                ('veterinario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
