# Generated by Django 6.0.5 on 2026-06-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0003_initial'),
        ('paciente', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestra',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muestra',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='muestras', to='paciente.paciente'),
        ),
        migrations.AlterField(
            model_name='muestra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50),
        ),
    ]
